# devgagan
# Note if you are trying to deploy on vps then directly fill values in ("")

from os import getenv

# VPS --- FILL COOKIES 🍪 in """ ... """

INST_COOKIES = """
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.instagram.com        TRUE    /       TRUE    1783611437      ps_n    1
#HttpOnly_.instagram.com        TRUE    /       TRUE    1758220458      datr    Avm8Zmw64JpuiAWjRTrfNN1c
.instagram.com  TRUE    /       TRUE    1755196456      ig_nrcb 1
.instagram.com  TRUE    /       TRUE    1760472627      ds_user_id      10734950991
.instagram.com  TRUE    /       TRUE    1787256627      csrftoken       bzP4GZU8WY5A7G6koC1MW20NSCIeoU9X
#HttpOnly_.instagram.com        TRUE    /       TRUE    1755196458      ig_did  385707B3-04F5-4DC3-91D0-11CAD15CFBC2
#HttpOnly_.instagram.com        TRUE    /       TRUE    1753079883      ig_direct_region_hint   "CLN\05410734950991\0541784011186:01fe367c36ed329a6608eb201f2eaf7075dedcefa9989f32273e24baa78e46213201e405"
#HttpOnly_.instagram.com        TRUE    /       TRUE    1783611437      ps_l    1
.instagram.com  TRUE    /       TRUE    1753301426      wd      1920x911
.instagram.com  TRUE    /       TRUE    1758220457      mid     Zrz5AgALAAE2OCsrAXl_jTwDN4qo
#HttpOnly_.instagram.com        TRUE    /       TRUE    1784232627      sessionid       10734950991%3AhQM0Ad7Hyz4M7g%3A3%3AAYddgdEVc3Ylt4PoEkswBOS5NlYp6uIb-rI8D-J_lvE
#HttpOnly_.instagram.com        TRUE    /       TRUE    1752783030      rur     "HIL\05410734950991\0541784232733:01fe1942a6f7f4474e31b4fbb1a60696478fb9f39ca7804661476f4fe9925127aa39b21d"
"""

YTUB_COOKIES = """
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com  TRUE    /       TRUE    1785402645      __Secure-3PSID  g.a000yQg9s8i278Lkmt2Uw4MJWO2OqS1_JVkqv1DtAub8PUaaJePRiQ9deayfYkayLm1olGrpigACgYKAS8SARYSFQHGX2Mioy15czBh9kKcm9WFQfWlqRoVAUF8yKrjLkobe_c-9O8t1784CL8L0076
.youtube.com    TRUE    /       FALSE   1784232305      SIDCC   AKEyXzWjMxiWsJiSeML_1gpOK1gftqpbxEbjRKFMGygG-KDRjX-E5ExbncL2smJ3xm11w_dTuQ
.youtube.com    TRUE    /       FALSE   1785402645      SID     g.a000yQg9s8i278Lkmt2Uw4MJWO2OqS1_JVkqv1DtAub8PUaaJePR6RoAlMxUqW6UNV39iURvlQACgYKARsSARYSFQHGX2MiZyjuOYtfdVV9GRokuJjuaRoVAUF8yKpikBMOtCBeWGK2Y9j-LPL10076
#HttpOnly_.youtube.com  TRUE    /       TRUE    1784232305      __Secure-1PSIDTS        sidts-CjIB5H03P9EG-NMom9qpr9l3VA-PzT---xMZtMO3Cg77okPUn_EFIp4Zv7Y_oK6wg4mnlxAA
.youtube.com    TRUE    /       TRUE    1785402645      SAPISID PA5Rtfyc2CJo61xf/Acp-g-9gMLUOulMPW
#HttpOnly_.youtube.com  TRUE    /       TRUE    1784232305      __Secure-1PSIDCC        AKEyXzUodwQy-RXs8XDHwUVM8ql3Ye7dV_bpR64tFvOrTK2-g1ldu02lMmWRSv85H438lBHsgA
#HttpOnly_.youtube.com  TRUE    /       TRUE    1785402645      SSID    AZ6Th13BGpNwOeQ8I
.youtube.com    TRUE    /       TRUE    1785402645      __Secure-1PAPISID       PA5Rtfyc2CJo61xf/Acp-g-9gMLUOulMPW
#HttpOnly_.youtube.com  TRUE    /       TRUE    1785402645      __Secure-1PSID  g.a000yQg9s8i278Lkmt2Uw4MJWO2OqS1_JVkqv1DtAub8PUaaJePRwYT-Aun34R5_tIAXr5kMVAACgYKATESARYSFQHGX2MiZvVo5208tFIB--Apx34zsxoVAUF8yKoGHZlbTddYbvT92P5kwICL0076
.youtube.com    TRUE    /       TRUE    1785402645      __Secure-3PAPISID       PA5Rtfyc2CJo61xf/Acp-g-9gMLUOulMPW
#HttpOnly_.youtube.com  TRUE    /       TRUE    1784232305      __Secure-3PSIDCC        AKEyXzX3RD6yADUfumSC3V0rvYZp3AR7LQdBBhjA8_dS1anQEOyMVSMY67zdzFBD-HAxInaynA
#HttpOnly_.youtube.com  TRUE    /       TRUE    1784232305      __Secure-3PSIDTS        sidts-CjIB5H03P9EG-NMom9qpr9l3VA-PzT---xMZtMO3Cg77okPUn_EFIp4Zv7Y_oK6wg4mnlxAA
.youtube.com    TRUE    /       FALSE   1785402645      APISID  06s36hHrXSj_UvgD/AGOaRtaulSeHWXHIO
#HttpOnly_.youtube.com  TRUE    /       FALSE   1785402645      HSID    AOgo-agwbtY9QI7ad
#HttpOnly_.youtube.com  TRUE    /       TRUE    1782634848      LOGIN_INFO      AFmmF2swRAIgZM-QyB-l7il2iokstC50dFSoo7r55kg073-7xH3vAp4CIDvZCTMtcobmFYNP8zVHM8qqo34oR4DyCEGPi1f4q_zn:QUQ3MjNmeGVpeGdqZmhUdkJDdFRLM255dVoyQWhUUWRFVDBlR0tCZjd>
.youtube.com    TRUE    /       TRUE    1787255097      PREF    f6=40000000&tz=Asia.Calcutta&f7=100
"""

API_ID = int(getenv("API_ID", "26604598"))
API_HASH = getenv("API_HASH", "78431be042455065fcc95346f63d9a46")
BOT_TOKEN = getenv("BOT_TOKEN", "")
OWNER_ID = list(map(int, getenv("OWNER_ID", "7726783353").split()))
MONGO_DB = getenv("MONGO_DB", "")
LOG_GROUP = getenv("LOG_GROUP", "-1002664960140")
CHANNEL_ID = int(getenv("CHANNEL_ID", "-1002848881053"))
FREEMIUM_LIMIT = int(getenv("FREEMIUM_LIMIT", "30"))
PREMIUM_LIMIT = int(getenv("PREMIUM_LIMIT", "7726783353"))
WEBSITE_URL = getenv("WEBSITE_URL", "indianshortner.com")
AD_API = getenv("AD_API", "d0806eccd261c40514e4565083801933d772ea00")
STRING = getenv("STRING", None)
YT_COOKIES = getenv("YT_COOKIES", YTUB_COOKIES)
DEFAULT_SESSION = getenv("DEFAUL_SESSION", None)  # added old method of invite link joining
INSTA_COOKIES = getenv("INSTA_COOKIES", INST_COOKIES)
